/**
 * Golden-file parity for the vault export presets. The same fixture is checked
 * by the Rust exporter (`vault_export.rs` tests), so the desktop batch
 * exporter and this JS fallback must produce byte-identical notes.
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { buildBookPageMarkdown, buildBookPages, buildVocabularyMarkdown } from "../src/core/lib/vault-sync";
import type { Annotation, Book, RssArticle, VaultExportPreset, VocabularyTerm } from "../src/core/types";

const dir = join(process.cwd(), "tests/fixtures/vault");
const input = JSON.parse(readFileSync(join(dir, "book-page-input.json"), "utf8")) as {
    source: { id: string; title: string; author: string; format: string; filePath: string };
    annotations: Annotation[];
};

describe.each<VaultExportPreset>(["obsidian", "logseq", "minimalist"])("vault preset %s", (preset) => {
    it("matches the shared golden file", () => {
        const expected = readFileSync(join(dir, `book-page-expected-${preset}.md`), "utf8");
        expect(buildBookPageMarkdown(input.source, input.annotations, undefined, preset)).toBe(expected);
    });

    it("does not depend on input order", () => {
        const reversed = [...input.annotations].reverse();
        expect(buildBookPageMarkdown(input.source, reversed, undefined, preset))
            .toBe(buildBookPageMarkdown(input.source, input.annotations, undefined, preset));
    });

    it("writes the empty-state note when there are no annotations", () => {
        const md = buildBookPageMarkdown(input.source, [], undefined, preset);
        expect(md).toContain("total_highlights: 0");
        expect(md.endsWith("_No highlights yet._\n")).toBe(true);
    });
});

describe("vault preset edge cases", () => {
    const base = { bookId: "b", createdAt: "2026-01-01T00:00:00.000Z" } as const;

    it("keeps Logseq notes inside their block (no unindented continuation lines)", () => {
        const md = buildBookPageMarkdown(input.source, [
            { ...base, id: "x", type: "highlight", selectedText: "q", noteContent: "one\ntwo\n\nthree" } as unknown as Annotation,
        ], undefined, "logseq");
        const body = md.split("## Highlights\n\n")[1];
        for (const line of body.split("\n").filter(Boolean)) {
            expect(line.startsWith("- ") || line.startsWith("  ")).toBe(true);
        }
    });

    it("falls back to Obsidian for unknown presets", () => {
        const annotations = [{ ...base, id: "x", type: "highlight", selectedText: "q" } as unknown as Annotation];
        expect(buildBookPageMarkdown(input.source, annotations, undefined, "bogus" as VaultExportPreset))
            .toBe(buildBookPageMarkdown(input.source, annotations, undefined, "obsidian"));
    });
});

describe("vault export parity with the native exporter", () => {
    // Golden files are generated by `full_export_matches_shared_golden_files`
    // in `src-tauri/src/vault_export.rs`.
    const expectedDir = join(dir, "export-expected");
    const payload = JSON.parse(readFileSync(join(dir, "export-input.json"), "utf8")) as {
        books: Book[];
        annotations: Annotation[];
        vocabularyTerms: VocabularyTerm[];
        rssArticles: RssArticle[];
    };

    it("writes the same note paths and contents", () => {
        const pages = buildBookPages(payload.books, payload.rssArticles, payload.annotations, "/vault/Theorem/Books");
        const produced = new Map<string, string>();
        for (const page of pages) {
            produced.set(`Books/${page.fileName}`, buildBookPageMarkdown(page.source, page.annotations, undefined, "obsidian"));
        }
        produced.set("Vocabulary.md", buildVocabularyMarkdown(payload.vocabularyTerms));

        const index = JSON.parse(readFileSync(join(expectedDir, "index.json"), "utf8")) as string[];
        expect([...produced.keys()].sort()).toEqual([...index].sort());
        for (const [rel, content] of produced) {
            expect(content, rel).toBe(readFileSync(join(expectedDir, rel), "utf8"));
        }
    });

    it("assigns collision suffixes independent of annotation order", () => {
        const forward = buildBookPages(payload.books, payload.rssArticles, payload.annotations, "/v");
        const backward = buildBookPages(payload.books, payload.rssArticles, [...payload.annotations].reverse(), "/v");
        const names = (pages: typeof forward) => new Map(pages.map((p) => [p.source.id, p.fileName]));
        expect(names(backward)).toEqual(names(forward));
    });
});
